stages:
  - prepare
  - build
  - upload

variables:
  # This is used to actually get the ci_scripts submodule
  GIT_SUBMODULE_STRATEGY: normal
  GIT_STRATEGY: clone


integration_repository:
  stage: prepare
  image: shadowrobot/build-tools:xenial-kinetic
  tags:
    - docker
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@ids-git.fzi.de/continuous_integration/ci_scripts .ci_scripts
  artifacts:
    paths:
      - .ci_scripts/

sr-build-tools-build_xenial:
  stage: build
  image: shadowrobot/build-tools:xenial-kinetic
  dependencies:
    - integration_repository
  tags:
    - docker
  script:
    - export ubuntu_version_name="xenial"
    - export ros_release_name="kinetic"
    - .ci_scripts/catkin_build_scripts/run_sr_build.sh
  artifacts:
    paths:
      - unit_tests/
      - code_coverage/
      - lint_results/
      - debs/
  coverage: '/Coverage: ([0-9.]+)/'

upload_xenial_debs:
  stage: upload
  image: ros:kinetic
  dependencies:
    - integration_repository
    - sr-build-tools-build_xenial
  only:
    refs:
      - master
  tags:
    - docker
  script:
    - export ubuntu_version_name="xenial"
    - export ros_release_name="kinetic"
    - apt-get update
    - apt-get install python-pip curl -y
    - pip install -U gitpython
    - git submodule add ../../continuous_integration/ci_scripts.git .ci_scripts
    - .ci_scripts/catkin_build_scripts/upload_deb_packages.sh debs
    - .ci_scripts/catkin_build_scripts/create_rosdistro_entry.py -o rosdistro_entry.json .
    - .ci_scripts/catkin_build_scripts/update_rosdistro.sh rosdistro_entry.json
